### ISSUE TITLE
Where should images be saved

### ISSUE THREAD

**Issue by gotenxds** [NoxNoctis/DWGMManager#11]
Where should we save images such as user profile pic, icons, maps, etc...

We can save them on the DB in 64Base

Or we can save them on the server, and save just a name/link in the DB

**Comment by NoxNoctis** [comment]
Seems like saving the files on the server and saving the name, type & file path in the DB is both the better and the easier method.

**Comment by gotenxds** [comment]
Yup, after reading a bit about it it seems to be the best course of action.
